### PR TITLE
Fix recursion error non-descriptive

### LINKED ISSUE #12: When there's an infinite recursion in a query the Error sign is not very descriptive
That's because prolog catches de error when mumukit finishes the process due to timeout.

### PR DESCRIPTION
**Pull request by gcrespi**
Fixes #12

### CODE REVIEW

File: query/query_runner.pl [hunk 1]
```diff
@@ -15,10 +15,13 @@
 handleQueryError(syntax_error(TypeSintaxError), Query):-
 	writef('ERROR: run_query/1: Sintax Error: %w in %w\n', [TypeSintaxError, Query]).
 
+handleQueryError(signal(_,Number), _):-
+	SignalStatus is 128 + Number,
+	halt(SignalStatus).
+
 handleQueryError(GeneralError, Query):-
```
Comment (flbulgarelli) [inline query/query_runner.pl]: Awesome!
